Repository puppypawpaw/pawpaw-client, pull requests merged in 2023-08, with the labels that each got.

#16 Chore
  app/(main)/layout.tsx
  app/(main)/page.tsx
  app/layout.tsx
  components/ui/Sidebar/Responsive/ResponsiveNavbar.tsx
  components/ui/Sidebar/SideButton/DesktopSvg.tsx
  components/ui/Sidebar/Sidebar.tsx
  public/sidebar/mobile/mobile_logo.svg
  service/.gitkeep
Labels: 🔨 Refactor

#18 Feat/feed page
  app/(main)/page.tsx
  app/layout.tsx
  components/pages/Feed/index.tsx
  components/ui/Avatar/index.tsx
  components/ui/Feed/FeedHeader/Location.tsx
  components/ui/Feed/FeedHeader/Title.tsx
  components/ui/Feed/FeedHeader/Upload.tsx
  components/ui/Feed/FeedHeader/index.tsx
  components/ui/Feed/PostsList/PostComment.tsx
  components/ui/Feed/PostsList/PostContent.tsx
  components/ui/Feed/PostsList/PostHeader.tsx
  components/ui/Feed/PostsList/index.tsx
  hooks/queries/.gitkeep
  hooks/queries/InfiniteData.tsx
  hooks/queries/PostCommentsQuery.tsx
  hooks/queries/ReactQueryProvider.tsx
  package.json
  public/Feed/desktop/breakLine.svg
  public/Feed/desktop/commentLine.svg
  public/Feed/desktop/currentPlaceBtn.svg
  public/Feed/desktop/like.svg
  public/Feed/desktop/seeMore.svg
  public/Feed/desktop/tempPostPic/tempPostPic1.svg
  public/Feed/desktop/tempPostPic/tempPostPic2.svg
  public/Feed/desktop/tempPostPic/tempPostPic3.svg
  public/Feed/desktop/tempProfilePic.svg
  public/Feed/desktop/tempUserProfilePic.svg
  service/tempPostListApi.tsx
  styles/global.css
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#19 Feat/entered chat card
  app/(main)/layout.tsx
  app/(main)/page.tsx
  components/pages/Feed/index.tsx
  components/pages/main/ChatCardList.tsx
  components/ui/Avatar/index.tsx
  components/ui/ChatCard/ChatCardHeader.tsx
  components/ui/ChatCard/ChatCardInfo.tsx
  components/ui/ChatCard/ChatCardTitle.tsx
  components/ui/ChatCard/index.tsx
  components/ui/Divider/index.tsx
  components/ui/EnteredChatCard/index.tsx
  components/ui/Sidebar/Sidebar.tsx
  components/ui/Tag/index.tsx
  components/ui/TagList/index.tsx
  public/ChatCard/arrow-left.svg
  public/ChatCard/arrow-right.svg
  public/ChatCard/notice.svg
  public/ChatCard/schedule.svg
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor, 👩🏼‍💻Fix

#22 Feat/feed page
  .eslintrc.json
  app/(main)/page.tsx
  components/pages/Feed/index.tsx
  components/pages/main/ChatCardList.tsx
  components/pages/main/Feed.tsx
  components/ui/Avatar/index.tsx
  components/ui/Badge/index.tsx
  components/ui/Button/index.tsx
  components/ui/ChatCard/ChatCardHeader.tsx
  components/ui/ChatCard/ChatCardInfo.tsx
  components/ui/ChatCard/index.tsx
  components/ui/Divider/index.tsx
  components/ui/EnteredChatCard/index.tsx
  components/ui/Feed/FeedHeader/Location.tsx
  components/ui/Feed/FeedHeader/Upload.tsx
  components/ui/Feed/FeedHeader/index.tsx
  components/ui/Feed/PostsList/PostComment.tsx
  components/ui/Feed/PostsList/PostContent.tsx
  components/ui/Feed/PostsList/PostHeader.tsx
  components/ui/Feed/PostsList/index.tsx
  components/ui/FlexBox/index.tsx
  components/ui/Sidebar/BottomToggle.tsx
  components/ui/Sidebar/Responsive/Footer/Footer.tsx
  components/ui/Sidebar/Responsive/Footer/FooterButton.tsx
  components/ui/Sidebar/Responsive/Header/Header.tsx
  components/ui/Sidebar/Responsive/Header/HeaderLogo.tsx
  components/ui/Sidebar/Responsive/MobileSvg.tsx
  components/ui/Sidebar/Responsive/ResponsiveNavbar.tsx
  components/ui/Sidebar/SideButton/DesktopSvg.tsx
  components/ui/Sidebar/SideButton/SideButton.tsx
  components/ui/Sidebar/SideButtonContainer.tsx
  components/ui/Sidebar/Sidebar.tsx
  components/ui/Sidebar/SidebarLogo.tsx
  components/ui/TagList/index.tsx
Labels: 👩🏼‍💻Fix

#23 Feat/comunity page
  app/(main)/community/page.tsx
  app/(main)/layout.tsx
  app/(main)/page.tsx
  components/pages/community/Carousel.tsx
  components/pages/community/EnteredChatList.tsx
  components/pages/community/RecommendChatList.tsx
  components/pages/community/TrendingChatList.tsx
  components/ui/Button/index.tsx
  components/ui/ChatCard/ChatCardHeader.tsx
  components/ui/ChatCard/ChatCardInfo.tsx
  components/ui/ChatCard/index.tsx
  components/ui/EnteredChatCard/index.tsx
  components/ui/Tag/index.tsx
  package.json
  styles/global.css
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css

#24 Feat/sidebar
  components/ui/Sidebar/BottomToggle.tsx
  components/ui/Sidebar/Responsive/Footer/Footer.tsx
  components/ui/Sidebar/Responsive/Footer/FooterButton.tsx
  components/ui/Sidebar/Responsive/Header/Header.tsx
  components/ui/Sidebar/Responsive/ResponsiveNavbar.tsx
  components/ui/Sidebar/SideButton/DesktopSvg.tsx
  components/ui/Sidebar/SideButton/SideButton.tsx
  components/ui/Sidebar/SideButtonContainer.tsx
  components/ui/Sidebar/Sidebar.tsx
  public/sidebar/desktop/Pawzone.svg
  types/types.ts
Labels: ✨ Feature, 🎨 Html&css, 👩🏼‍💻Fix

#31 Feat/chat room
  app/(main)/chat/[roomId]/page.tsx
  app/(main)/page.tsx
  components/pages/chat/AvatarGroup.tsx
  components/pages/chat/ChatRoom.tsx
  components/pages/chat/ChatRoomBox.tsx
  components/pages/chat/ChatRoomHeader.tsx
  components/pages/chat/ChatUser.tsx
  components/pages/chat/ChatUserList.tsx
  components/pages/chat/Message.tsx
  components/pages/chat/MessageInput.tsx
  components/pages/chat/Schedule.tsx
  components/pages/chat/ScheduleCard.tsx
  package.json
  public/PaperPlaneTilt.svg
  public/PlusCircle.svg
  public/arrow-left.svg
  public/arrow-right.svg
  public/export.svg
  public/hambuger-menu.svg
  public/tabler_dots.svg
  tailwind.config.js
  yarn.lock
Labels: 🎨 Html&css

#32 Refactor/main
  app/(main)/page.tsx
  app/layout.tsx
  components/pages/main/RecommendPlace.tsx
  components/pages/main/SimpleChatCard.tsx
  components/pages/main/SimpleChatCardList.tsx
  components/ui/Badge/index.tsx
  package.json
  public/ArrowClockwise.svg
  service/.gitkeep
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#34 Design/DesignSystem
  styles/global.css
Labels: 🎨 Html&css

#35 Feat/Dropdown Component
  app/(main)/chat/[roomId]/page.tsx
  components/pages/chat/ChatDropdownButton.tsx
  components/pages/chat/ChatRoom.tsx
  components/pages/chat/ChatRoomBox.tsx
  components/pages/chat/ChatRoomHeader.tsx
  components/pages/chat/ChatUser.tsx
  components/pages/chat/ScheduleCard.tsx
  components/pages/chat/ScheduleDropdownButton.tsx
  components/pages/chat/ScheduleList.tsx
  components/pages/chat/ScheduleListModal.tsx
  components/pages/chat/UserListModal.tsx
  components/pages/main/RecommendPlace.tsx
  components/pages/main/SimpleChatCard.tsx
  components/ui/ChatCard/index.tsx
  components/ui/Dropdown/Dropdown.tsx
  components/ui/Dropdown/Item.tsx
  components/ui/Dropdown/Menu.tsx
  components/ui/Dropdown/Trigger.tsx
  hooks/common/useOutSideClick.ts
  public/share.svg
  utils/Portal.tsx
Labels: ✨ Feature
