Repository puppypawpaw/pawpaw-client, pull requests merged in 2023-10, with the labels that each got.

#60 Feat/feed page
  app/layout.tsx
  components/pages/main/Feed.tsx
  components/pages/main/Feed/FeedHeader/Location.tsx
  components/pages/main/Feed/FeedHeader/Title.tsx
  components/pages/main/Feed/FeedHeader/Upload.tsx
  components/pages/main/Feed/FeedHeader/index.tsx
  components/pages/main/Feed/PostsList/PostCard/FeedPostCard.tsx
  components/pages/main/Feed/PostsList/PostCard/ModalPostCard.tsx
  components/pages/main/Feed/PostsList/PostModal.tsx
  components/pages/main/Feed/PostsList/index.tsx
  components/pages/main/Feed/index.tsx
  components/ui/Button/index.tsx
  components/ui/ChatCard/NormalChatCard.tsx
  components/ui/Feed/PostsList/PostCommentWrapper.tsx
  components/ui/Feed/PostsList/PostContent.tsx
  components/ui/Feed/PostsList/PostHeader.tsx
  components/ui/Feed/PostsList/PostModal/ModalComments.tsx
  components/ui/Feed/PostsList/PostModal/ModalContent.tsx
  components/ui/Feed/PostsList/PostModal/index.tsx
  components/ui/Feed/PostsList/index.tsx
  components/ui/PostCard/CommentWrapper.tsx
  components/ui/PostCard/Comments.tsx
  components/ui/PostCard/Content.tsx
  components/ui/PostCard/Header.tsx
  components/ui/PostCard/Images.tsx
  components/ui/PostCard/ModalComments.tsx
  components/ui/PostCard/ModalContent.tsx
  components/ui/PostCard/PostCardDropdown.tsx
  components/ui/PostCard/index.tsx
  package.json
  public/Alert.svg
  public/Check.svg
  public/DotsIcon.svg
  styles/global.css
  tailwind.config.js
  utils/copyToClipBoard.ts
  utils/copyURL.ts
  utils/notification.tsx
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#61 Fix: ToastContainer컴포넌트 body 안으로, Toast 반응형 #51
  app/layout.tsx
  components/pages/main/Feed/PostsList/PostCard/FeedPostCard.tsx
  components/pages/main/Feed/index.tsx
  components/ui/PostCard/Comments.tsx
  service/user.ts
  styles/global.css
Labels: 🐞 BugFix, ✨ Feature

#63 Fix:proxy 수정
  components/pages/main/Sidebar/Sidebar.tsx
  components/ui/Modal/AddChatRoomModal/index.tsx
  hooks/queries/useGetChatRoomUsetList.ts
  next.config.js
  service/chatRoom.ts
  service/community.ts
  service/user.ts
Labels: 🐞 BugFix

#62 Feat/auth - 일반(간편) 회원가입 / 이메일 로그인 구현
  app/auth/email-login/page.tsx
  app/auth/identity/page.tsx
  app/auth/layout.tsx
  app/auth/location/page.tsx
  app/auth/login/page.tsx
  app/auth/policy/page.tsx
  app/auth/profile/page.tsx
  app/auth/register/page.tsx
  components/pages/auth/CheckListOfTerm.tsx
  components/pages/auth/Complete/index.tsx
  components/pages/auth/ConfirmIdentity/ConfirmForm.tsx
  components/pages/auth/ConfirmIdentity/index.tsx
  components/pages/auth/EmailLogin/index.tsx
  components/pages/auth/Location/index.tsx
  components/pages/auth/LocationList.tsx
  components/pages/auth/Policy/index.tsx
  components/pages/auth/Profile/index.tsx
  components/pages/auth/ProgressBar.tsx
  components/pages/auth/Register/AuthForm.tsx
  components/pages/auth/Register/index.tsx
  components/ui/Input/SelectInput/index.tsx
  components/ui/Input/ValidateInput/index.tsx
  constant/pets.ts
  hooks/stores/useGeneralRegisterStore.ts
  hooks/stores/useIdentityStore.ts
  hooks/stores/useRegisterStore.ts
  package.json
  public/Auth/alert.svg
  service/auth.ts
  styles/global.css
  types/types.ts
  utils/common.ts
  utils/validate.ts
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#66 Feat/채팅룸스케줄api연결
  app/(main)/chat/[roomId]/page.tsx
  components/pages/chat/ChatRoom/ChatDropdownButton.tsx
  components/pages/chat/ChatRoom/ChatUser.tsx
  components/pages/chat/ChatRoom/ChatUserList.tsx
  components/pages/chat/ChatRoom/ChatUserListMobile.tsx
  components/pages/chat/ChatRoom/UserAddButton.tsx
  components/pages/chat/Schedule/AvatarGroup.tsx
  components/pages/chat/Schedule/ScheduleCard.tsx
  components/pages/chat/Schedule/ScheduleDropdownButton.tsx
  components/pages/chat/Schedule/ScheduleList.tsx
  components/pages/chat/Schedule/ScheduleListMobile.tsx
  components/ui/Input/SearchInput/index.tsx
  components/ui/Loading/ChatUserListLoading.tsx
  components/ui/Modal/AddChatRoomModal/index.tsx
  components/ui/Modal/LeaveChatRoomModal/index.tsx
  components/ui/Modal/ScheduleAddModal/ScheduleAddModal.tsx
  components/ui/Modal/UserAddModal/SearchedUserList.tsx
  components/ui/Modal/UserAddModal/UserAddModal.tsx
  components/ui/Modal/index.tsx
  hooks/mutations/useCreateSchedule.ts
  hooks/mutations/useDeleteSchedule.ts
  hooks/mutations/useInviteUserToChatroom.ts
  hooks/mutations/useJoinSchedule.ts
  hooks/mutations/useWithdrawSchedule.ts
  hooks/queries/useGetChatRoomUserList.ts
  hooks/queries/useGetChatRoomUsetList.ts
  hooks/queries/useGetScheduleList.ts
  hooks/queries/useGetSearchedUserList.ts
  hooks/queries/useGetUserInfo.ts
  lib/error.ts
  package.json
  public/CrownSimple.svg
  service/chatRoom.ts
  types/types.ts
  yarn.lock
Labels: ✨ Feature

#70 Feat/auth rwd
  app/(main)/community/page.tsx
  app/(main)/page.tsx
  app/auth/layout.tsx
  app/auth/login/page.tsx
  components/pages/auth/BottomButton.tsx
  components/pages/auth/CheckList.tsx
  components/pages/auth/ConfirmIdentity/ConfirmForm.tsx
  components/pages/auth/EmailLogin/index.tsx
  components/pages/auth/LocationList.tsx
  components/pages/auth/Profile/index.tsx
  components/pages/auth/SocialButton.tsx
  components/ui/Input/SearchInput/index.tsx
  components/ui/Input/ValidateInput/index.tsx
  public/Auth/desktop-logo.svg
  public/Auth/google.svg
  public/Auth/kakao.svg
  public/Auth/naver.svg
  public/ChatCard/dog.svg
  tailwind.config.js
Labels: 🎨 Html&css

#74 Feat/Find_ID_Change_PWD - 아이디 찾기 / 비밀번호 변경
  app/(main)/page.tsx
  app/auth/email-login/page.tsx
  app/auth/find-change/page.tsx
  app/auth/login/page.tsx
  app/auth/pwchange/page.tsx
  components/pages/auth/EmailLogin/index.tsx
  components/pages/auth/FindChange/TabButton.tsx
  components/pages/auth/FindChange/index.tsx
  components/pages/auth/Profile/index.tsx
  components/pages/auth/PwdChange/index.tsx
  components/pages/auth/SocialButton.tsx
  components/pages/main/layout/Sidebar/BottomButtonContainer.tsx
  components/ui/Modal/AddChatRoomModal/index.tsx
  components/ui/Modal/ScheduleAddModal/ScheduleAddModal.tsx
  components/ui/Modal/UserAddModal/UserAddModal.tsx
  hooks/stores/useGeneralRegisterStore.ts
  middleware.ts
  package.json
  public/X.svg
  service/auth.ts
  service/map.ts
  types/types.ts
  yarn.lock
Labels: ✨ Feature, 👩🏼‍💻Fix

#77 Fix/Auth_Bug - 인증 페이지 관련 각종 버그 픽스
  components/pages/auth/BottomButton.tsx
  components/pages/auth/ConfirmIdentity/ConfirmForm.tsx
  components/pages/auth/EmailLogin/index.tsx
  components/pages/auth/FindChange/index.tsx
  components/pages/auth/Profile/index.tsx
  components/pages/auth/Register/AuthForm.tsx
  components/pages/auth/SocialButton.tsx
  components/pages/main/layout/Sidebar/BottomButtonContainer.tsx
  service/auth.ts
  types/types.ts
Labels: 👩🏼‍💻Fix

#75 Refactor/chat
  app/(main)/community/error.tsx
  app/(main)/community/page.tsx
  app/(main)/page.tsx
  app/layout.tsx
  app/not-found.tsx
  components/pages/chat/ChatRoom/ChatItem.tsx
  components/pages/chat/ChatRoom/ChatRoom.tsx
  components/pages/chat/ChatRoom/ChatRoomBox.tsx
  components/pages/chat/ChatRoom/ChatUserList.tsx
  components/pages/chat/ChatRoom/DeleteChatRoomButton.tsx
  components/pages/community/EnteredChatList.tsx
  components/pages/community/TrendingChatList.tsx
  components/pages/main/RecommendPlace.tsx
  components/pages/main/SimpleChatCardList.tsx
  components/ui/ChatCard/ImageChatCard.tsx
  components/ui/ChatCard/NormalChatCard.tsx
  components/ui/ChatCard/SimpleChatCard.tsx
  components/ui/ChatCard/index.tsx
  components/ui/Loading/EnteredChatLoading.tsx
  components/ui/Loading/SimpleChatListLoading.tsx
  components/ui/Modal/OwnerDelegationModal/index.tsx
  components/ui/Modal/UserAddModal/SearchedUserList.tsx
  components/ui/Modal/UserAddModal/UserAddModal.tsx
  constant/chat.ts
  constant/query-keys.ts
  hooks/common/useChatScroll.ts
  hooks/mutations/useCreateSchedule.ts
  hooks/mutations/useDelegateRoomOwner.ts
  hooks/mutations/useDeleteSchedule.ts
  hooks/mutations/useInviteUserToChatroom.ts
  hooks/mutations/useJoinSchedule.ts
  hooks/mutations/useWithdrawSchedule.ts
  hooks/queries/useGetChatHistory.ts
  hooks/queries/useGetChatRoomUserList.ts
  hooks/queries/useGetEnteredChatList.ts
  hooks/queries/useGetRecommendChatList.ts
  hooks/queries/useGetScheduleList.ts
  hooks/queries/useGetSearchedUserList.ts
  hooks/queries/useGetTrendingChatList.tsx
  hooks/queries/useGetUserInfo.ts
  public/image.png
  service/chatRoom.ts
  service/community.ts
  types/types.ts
Labels: 🔨 Refactor

#79 Refactor/error handling
  components/ui/DatePicker/Date.tsx
  components/ui/DatePicker/Month.tsx
  components/ui/Modal/AddChatRoomModal/index.tsx
  components/ui/Modal/ImageUploadModal/index.tsx
  hooks/mutations/useCreateSchedule.ts
  hooks/mutations/useDelegateRoomOwner.ts
  hooks/mutations/useDeleteSchedule.ts
  hooks/mutations/useInviteUserToChatroom.ts
  hooks/mutations/useJoinSchedule.ts
  hooks/mutations/useWithdrawSchedule.ts
  hooks/queries/ReactQueryProvider.tsx
  service/chatRoom.ts
Labels: 🔨 Refactor
