Repository puppypawpaw/pawpaw-client, pull requests merged in 2023-09, with the labels that each got.

#42 Feat/sidebar
  .env
  .eslintrc.json
  app/(main)/layout.tsx
  components/pages/main/Sidebar/BottomToggle.tsx
  components/pages/main/Sidebar/Responsive/Footer/Footer.tsx
  components/pages/main/Sidebar/Responsive/Footer/FooterButton.tsx
  components/pages/main/Sidebar/Responsive/Header/Header.tsx
  components/pages/main/Sidebar/Responsive/Header/HeaderLogo.tsx
  components/pages/main/Sidebar/Responsive/MobileSvg.tsx
  components/pages/main/Sidebar/Responsive/ResponsiveNavbar.tsx
  components/pages/main/Sidebar/SideButton/DesktopSvg.tsx
  components/pages/main/Sidebar/SideButton/SideButton.tsx
  components/pages/main/Sidebar/SideButtonContainer.tsx
  components/pages/main/Sidebar/Sidebar.tsx
  components/pages/main/Sidebar/SidebarLogo.tsx
  components/pages/main/Sidebar/hooks/useGetPathname.ts
  components/ui/Modal/ModalContentWrapper.tsx
  components/ui/Sidebar/BottomToggle.tsx
  hooks/common/useViewportTracker.ts
  public/sidebar/desktop/MagnifyingGlass.svg
  public/sidebar/desktop/MapPin.svg
  public/sidebar/desktop/UserCircle.svg
  public/sidebar/desktop/chat.svg
  public/sidebar/desktop/community.svg
  public/sidebar/desktop/feed.svg
  public/sidebar/desktop/logout.svg
  public/sidebar/desktop/mypage.svg
  public/sidebar/desktop/search.svg
  public/sidebar/mobile/MapPin.svg
  types/types.ts
Labels: 🔨 Refactor

#43 Design/design system
  components/ui/Modal/Modal.tsx
  styles/global.css
  tailwind.config.js
Labels: 🎨 Html&css, 👩🏼‍💻Fix

#44 Refactor/chat room
  app/(main)/chat/[roomId]/page.tsx
  app/(main)/page.tsx
  components/pages/chat/ChatDropdownButton.tsx
  components/pages/chat/ChatRoom/ChatDropdownButton.tsx
  components/pages/chat/ChatRoom/ChatRoom.tsx
  components/pages/chat/ChatRoom/ChatRoomBox.tsx
  components/pages/chat/ChatRoom/ChatRoomHeader.tsx
  components/pages/chat/ChatRoom/ChatUser.tsx
  components/pages/chat/ChatRoom/ChatUserList.tsx
  components/pages/chat/ChatRoom/ChatUserListMobile.tsx
  components/pages/chat/ChatRoom/Message.tsx
  components/pages/chat/ChatRoom/MessageInput.tsx
  components/pages/chat/ChatRoom/UserAddButton.tsx
  components/pages/chat/ChatUser.tsx
  components/pages/chat/ChatUserList.tsx
  components/pages/chat/Modal/LeaveChatRoomModal.tsx
  components/pages/chat/Modal/SearchedUserList.tsx
  components/pages/chat/Modal/UserAddModal.tsx
  components/pages/chat/Schedule/AvatarGroup.tsx
  components/pages/chat/Schedule/ScheduleCard.tsx
  components/pages/chat/Schedule/ScheduleDropdownButton.tsx
  components/pages/chat/Schedule/ScheduleList.tsx
  components/pages/chat/Schedule/ScheduleListMobile.tsx
  components/pages/chat/UserListModal.tsx
  components/pages/community/Carousel.tsx
  components/pages/community/EnteredChatList.tsx
  components/pages/community/RecommendChatList.tsx
  components/pages/community/TrendingChatList.tsx
  components/pages/main/RecommendPlace.tsx
  components/pages/main/SimpleChatCard.tsx
  components/pages/main/SimpleChatCardList.tsx
  components/ui/Avatar/index.tsx
  components/ui/Badge/index.tsx
  components/ui/Button/index.tsx
  components/ui/ChatCard/ChatCardHeader.tsx
  components/ui/ChatCard/ChatCardInfo.tsx
  components/ui/ChatCard/ImageChatCard.tsx
  components/ui/ChatCard/NormalChatCard.tsx
  components/ui/ChatCard/SimpleChatCard.tsx
  components/ui/ChatCard/index.tsx
  components/ui/Dropdown/Dropdown.tsx
  components/ui/Dropdown/Item.tsx
  components/ui/Dropdown/Menu.tsx
  components/ui/EnteredChatCard/index.tsx
  components/ui/Feed/FeedHeader/Upload.tsx
  components/ui/Feed/PostsList/PostHeader.tsx
  components/ui/Modal/Modal.tsx
  components/ui/SearchInput/index.tsx
  hooks/common/useCheckbox.ts
  hooks/common/useInput.ts
  package.json
  public/Badge.svg
  public/X.svg
  public/input-delete.svg
  public/search.svg
  tailwind.config.js
  utils/Portal.tsx
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#49 Feat/add schedule
  .eslintrc.json
  app/(main)/chat/[roomId]/page.tsx
  components/pages/chat/ChatRoom/ChatRoom.tsx
  components/pages/chat/Modal/ScheduleAddModal.tsx
  components/pages/chat/Modal/TimeSelect.tsx
  components/pages/chat/Schedule/ScheduleDropdownButton.tsx
  components/ui/Button/index.tsx
  components/ui/DatePicker/Date.tsx
  components/ui/DatePicker/Month.tsx
  components/ui/DatePicker/index.tsx
  components/ui/Dropdown/Item.tsx
  components/ui/Select/Option.tsx
  components/ui/Select/OptionList.tsx
  components/ui/Select/Trigger.tsx
  components/ui/Select/Value.tsx
  components/ui/Select/index.tsx
  constant/days.ts
  hooks/common/useCalender.ts
  package.json
  public/CaretDown.svg
  public/CaretLeft.svg
  public/CaretRight.svg
  public/arrow-left.svg
  public/arrow-right.svg
  public/combobox-arrow.svg
  styles/global.css
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#53 Fix/add schedule
  components/pages/chat/Modal/ScheduleAddModal.tsx
  components/pages/chat/Modal/TimeSelect.tsx
  components/pages/chat/Schedule/ScheduleListMobile.tsx
  components/ui/Button/index.tsx
  components/ui/DatePicker/Date.tsx
  components/ui/DatePicker/DatePickerWrapper.tsx
  components/ui/DatePicker/Month.tsx
  components/ui/DatePicker/index.tsx
  components/ui/Select/OptionList.tsx
  components/ui/Select/Trigger.tsx
  components/ui/Select/index.tsx
  public/arrow-right.svg
Labels: 🔨 Refactor, 👩🏼‍💻Fix

#56 Feat/add chat room
  app/(main)/community/page.tsx
  app/(main)/layout.tsx
  components/pages/chat/ChatRoom/ChatRoom.tsx
  components/pages/chat/ChatRoom/ChatUserListMobile.tsx
  components/pages/chat/ChatRoom/UserAddButton.tsx
  components/pages/chat/Modal/ScheduleAddModal.tsx
  components/pages/chat/Modal/SearchedUserList.tsx
  components/pages/chat/Modal/UserAddModal.tsx
  components/pages/community/AddChatRoomButton.tsx
  components/ui/Button/index.tsx
  components/ui/ChatCard/SimpleChatCard.tsx
  components/ui/Modal/index.tsx
  components/ui/ModalRefactor/AddChatRoomModal/HashTagInput.tsx
  components/ui/ModalRefactor/AddChatRoomModal/ImageDisplay.tsx
  components/ui/ModalRefactor/AddChatRoomModal/ImageList.tsx
  components/ui/ModalRefactor/AddChatRoomModal/MobileHeader.tsx
  components/ui/ModalRefactor/AddChatRoomModal/OptionRadioGroup.tsx
  components/ui/ModalRefactor/AddChatRoomModal/index.tsx
  components/ui/ModalRefactor/index.tsx
  components/ui/RadioGroup/Item.tsx
  components/ui/RadioGroup/index.tsx
  components/ui/Tag/index.tsx
  components/ui/ui.ts
  hooks/common/useImageUpload.ts
  hooks/common/useInput.ts
  package.json
  public/Camera.svg
  public/images/AddChatModal/default10.webp
  public/images/AddChatModal/default11.webp
  public/images/AddChatModal/default12.webp
  public/images/AddChatModal/default13.webp
  public/images/AddChatModal/default14.webp
  public/images/AddChatModal/default2.webp
  public/images/AddChatModal/default3.webp
  public/images/AddChatModal/default4.webp
  public/images/AddChatModal/default5.webp
  public/images/AddChatModal/default6.webp
  public/images/AddChatModal/default7.webp
  public/images/AddChatModal/default8.webp
  public/images/AddChatModal/default9.webp
  public/plus.svg
  service/chatRoom.ts
  tailwind.config.js
  types/types.ts
  yarn.lock
Labels: ✨ Feature
